compressionLevel: mixed

enableColors: true

enableGlobalCache: false

enableInlineHunks: true

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmRegistryServer: "http://registry.npmjs.org"

unsafeHttpWhitelist: registry.npmjs.org

yarnPath: .yarn/releases/yarn-4.4.1.cjs
